### ISSUE TITLE
connection pooling issue

### ISSUE THREAD

**Issue by bharathnallamothu** [ShankyTiwari/Real-time-private-chatting-app-using-Angular-Nodejs-mongodb-and-Socket.io#3]
integrated with 50k users db. server crashed due to db connections.

**Comment by ShankyTiwari** [comment]
Hey @bharathnallamothu, this app is not written for scaling and production, just demonstration purpose how one can create a private chat application

Coming to your problem, you apply some solutions I normally do for a large audience,
- Release a MySQL connection after the last query in any HTTP request.
- Use Master-Slave architecture, very useful.
- Divide the HTTP services into Micro Service (This couples with Master-Slave architecture very well). For example, here you can divide this Nodejs server into three parts
    1. Account/Auth Service
    2. Chat Service
    3. Socket Service (try not to perform any query in this service)
- Use pooling properly you can find many blog posts on the internet.
